medicamento/Controllers/MedicineController.cs
using medicamento.Models.Statistics;
using medicamento.Services.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace medicamento.Controllers
{
    public class MedicineController : Controller
    {
        private readonly ILogger<MedicineController> _logger;
        private readonly AppDbContext _context;

        public MedicineController(ILogger<MedicineController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [Route("Medicine/List/{param?}")]
        public async Task<IActionResult> List(string param)
        {
            var medicamento = await _context.Prescripcion
                .Where(m => m.des_comercial.Contains(param) || m.principios_activos.Contains(param) || m.cod_definitivo == param)
                .ToListAsync();
            return View(medicamento);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicamento = await _context.Prescripcion
                .FirstOrDefaultAsync(m => m.cod_nacional == id);

            if (medicamento == null)
            {
                return NotFound();
            }

            StatisticsModel statistics = new StatisticsModel
            {
                user_id = User.Identity.Name,
                key = "medicine",
                date = DateTime.Now,
                nro_registro = id,
                type = 1
            };

            _context.Statistics.Add(statistics);
            await _context.SaveChangesAsync();

            return View(medicamento);
        }

    }
}

medicamento/Controllers/OrdersController.cs
using medicamento.Models.ShoppingCart;
using medicamento.Services.DB;
using medicamento.ViewModels.Account;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace medicamento.Controllers
{
    public class OrdersController : Controller
    {
        private readonly AppDbContext _context;

        public OrdersController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Orders.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(order => order.OrderDetails)
                .ThenInclude(orderDetail => orderDetail.Medicine)
                .FirstOrDefaultAsync(m => m.OrderId == id);

            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Address,Email")] OrderModel order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Address,Email")] OrderModel model)
        {
            if (!ModelState.IsValid)
            {
                // Si la validación falla, vuelve a la vista con los errores
                return View(model);
            }

            var order = await _context.Orders.FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                // Si no se encuentra la orden, muestra error
                ModelState.AddModelError("", "Order not found.");
                return View(model);
            }

            // Actualiza solo los campos editables
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.Address = model.Address;
            order.Email = model.Email;

            try
            {
                _context.Update(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.Orders.Any(e => e.OrderId == id))
                {
                    ModelState.AddModelError("", "Order not fount.");
                    return View(model);
                }
                else
                {
                    throw;
                }
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }
    }
}

medicamento/Controllers/ShoppingCartController.cs
using medicamento.Services.DB;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using medicamento.Services.ShoppingCart;
using medicamento.ViewModels.ShoppingCart;
using medicamento.Models.ShoppingCart;

namespace medicamento.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ILogger<MedicineController> _logger;
        private readonly AppDbContext _context;
        public ShoppingCartController(ILogger<MedicineController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public ActionResult Index()
        {
            var pathBase = HttpContext;
            var cart = ShoppingCart.GetCart(pathBase);

            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            return View(viewModel);
        }

        public ActionResult AddToCart(string id)
        {
            var addedMedicine = _context.Prescripcion
                .Single(album => album.cod_nacional == id);

            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedMedicine);

            return RedirectToAction("Index");
        }

        //[HttpPost]
        //public ActionResult RemoveFromCart(int id)
        //{
        //    var cart = ShoppingCart.GetCart(this.HttpContext);

        //    string medicineName = _context.Carts.Single(item => item.RecordId == id).Medicine.des_comercial;

        //    int itemCount = cart.RemoveFromCart(id);

        //    var results = new ShoppingCartRemoveViewModel
        //    {
        //        Message = HttpUtility.HtmlEncode(medicineName) +
        //            " has been removed from your shopping cart.",
        //        CartTotal = cart.GetTotal(),
        //        CartCount = cart.GetCount(),
        //        ItemCount = itemCount,
        //        DeleteId = id
        //    };
        //    return Json(results);
        //}

        [System.Web.Mvc.ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("~/Views/Shared/_CartSummaryPartial");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateQuantity([FromBody] UpdateCartQuantityModel model)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.UpdateQuantity(model.Id, model.Quantity);
            
            return Json(new { success = true });
        }
        
        [HttpPost]
        public IActionResult RemoveFromCart([FromBody] RemoveFromCartModel request)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var cartItem = _context.Carts.FirstOrDefault(item => item.RecordId == request.Id);
            string medicineName = cartItem?.Medicine?.des_comercial ?? "El producto";
            bool result = cart.RemoveFromCart(request.Id);

            return Json(new { success = result, message = $"{medicineName} ha sido eliminado del carrito." });
        }

    }
}

medicamento/Controllers/UserController.cs
using medicamento.Models.Account;
using medicamento.Models.Account.Extensions;
using medicamento.ViewModels.Account;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace medicamento.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class UserController : Controller
    {
        private readonly UserManager<Users> userManager;

        public UserController(UserManager<Users> userManager)
        {
            this.userManager = userManager;
        }

        public async Task<ActionResult> Index()
        {
            var users = userManager.Users.ToList();
            var userRoles = new List<(Users User, IList<string> Roles)>();

            foreach (var user in users)
            {
                var roles = await userManager.GetRolesAsync(user);
                userRoles.Add((user, roles));
            }

            return View(userRoles);
            //return View(this.userManager.Users.ToList());
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        [Route("User/Edit/{userId}")]
        public async Task<ActionResult> Edit(string userId)
        {
            var user = await userManager.FindByIdAsync(userId);
            
            if (user == null)
            {
                return RedirectToAction("Index");
            }

            return View(user.ToViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, UpdateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(id);
                if (user == null)
                {
                    TempData["ErrorMessage"] = "User not found.";
                    return View(model);
                }
                var role = await userManager.GetRolesAsync(user);

                if (user.UserName != model.UserName)
                    user.FullName = model.FullName;
                
                if (user.FullName != model.FullName)
                    user.FullName = model.FullName;

                if (user.Email != model.Email)
                    user.Email = model.Email;

                if(!role.Contains(model?.Role))
                    await userManager.AddToRoleAsync(user, model.Role);

                var result = await userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                    ModelState.AddModelError("", error.Description);

            }

            return View(model);
          
        }

        public async Task<ActionResult> Delete(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                TempData["ErrorMessage"] = "User not found.";
                return RedirectToAction("Index");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMessage"] = string.Join(" ", result.Errors.Select(e => e.Description));
                    return RedirectToAction("Index");
                }

            }
        }
        
    }
}

medicamento/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"]</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.29.0/feather.min.js"
			crossorigin="anonymous"></script>
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body class="bg-gradient-default">
	<div id="layoutAuthentication">
		<div id="layoutAuthentication_content">
			<main>
				<div class="container-xl px-4">
		@RenderBody()
		</div>
		</main>
		</div>
		
	</div>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
	<script src="~/js/color-modes.js"></script>
	<script src="~/js/scripts.js"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

medicamento/Views/Shared/_CartSummary.cshtml
@using medicamento.Services.ShoppingCart
@using Microsoft.AspNetCore.Mvc;
@inject ShoppingCart cart;

@{
    var pathBase = Context;
    var cart = ShoppingCart.GetCart(pathBase);
}

<li class="nav-item dropdown no-caret d-none d-sm-block dropdown-notifications me-3">
    <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownMessages"
    href="javascript:void(0);" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
    aria-expanded="false">
        
    <i data-feather="shopping-cart"></i>
        <span id="cart-status" class="badge bg-secondary rounded-pill ms-1">@cart.GetCount()</span>
    </a>
        
    <div class="dropdown-menu dropdown-menu-end animated--fade-in-up border-0 shadow"
    aria-labelledby="navbarDropdownMessages">
        <h6 class="dropdown-header dropdown-notifications-header bg-secondary">
            <i class="me-2" data-feather="shopping-cart"></i>
            Cart Center
        </h6>
        
        @foreach (var item in @cart.GetCartItems())
        {
            <a class="dropdown-item dropdown-notifications-item" href="#!">
                @* <img class="dropdown-notifications-item-img"
                     src="assets/img/illustrations/profiles/profile-2.png" /> *@
                <div class="dropdown-notifications-item-content">
                    <div class="dropdown-notifications-item-content-text">
                        @item.Medicine.des_comercial
                    </div>
                </div>
            </a>
        }
       
        <a class="dropdown-item dropdown-notifications-footer" asp-controller="ShoppingCart" asp-action="Index">View All Items</a>
    </div>

medicamento/Views/Shared/_ErrorAlert.cshtml
@if (TempData["ErrorMessage"] != null)
{
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<strong>Error!</strong> @TempData["ErrorMessage"]
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
}

medicamento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"]</title>
	@* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous"> *@
	<link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.29.0/feather.min.js"
			crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/js/all.min.js" crossorigin="anonymous"></script>
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
		  rel="stylesheet">
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body id="page-top" class="nav-fixed">
	
	<partial name="_Navbar" />
	
	<div id="layoutSidenav">
		<partial name="_Sidebar" />

		<div id="layoutSidenav_content">
			<main>
				@RenderBody()
			</main>		
		</div>
		
	</div>

	<a class="scroll-to-top rounded" href="#page-top">
		<i class="bi bi-chevron-up"></i>
	</a>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js"
			crossorigin="anonymous"></script>
	<script src="~/js/datatables-simple-demo.js"></script>

	@* <script src="~/js/site.js" asp-append-version="true"></script> *@
	<script src="~/assets/demo/chart-area-demo.js"></script>
	<script src="~/assets/demo/chart-bar-demo.js"></script>
	@* <script src="~/js/color-modes.js"></script> *@
	<script src="~/js/scripts.js"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

medicamento/Views/Shared/_Navbar.cshtml
<nav class="topnav navbar navbar-expand justify-content-between justify-content-sm-start navbar-light bg-white shadow" id="sidenavAccordion">
    <!-- Sidenav Toggle Button-->
    <button class="btn btn-icon btn-transparent-dark order-lg-0 ms-lg-2 me-lg-0 order-1 me-2" id="sidebarToggle">
        <i data-feather="menu"></i>
    </button>
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-lg-2 pe-3 ps-4" href="index.html">Mutus</a>
    <!-- Navbar Search Input-->
    <form class="form-inline d-none d-lg-block me-3 me-auto" asp-controller="Medicine" asp-action="List" method="get">
        <div class="input-group input-group-joined input-group-solid">
            @* <input class="form-control pe-0" type="search" placeholder="Search" aria-label="Search" /> *@
            @Html.TextBox("Param", null, new { @class = "form-control pe-0", placeholder = "Search" })

            <div class="input-group-text"><i data-feather="search"></i></div>
        </div>
    </form>
    <!-- Navbar Items-->
    <ul class="navbar-nav align-items-center ms-auto">

        <!-- Navbar Search Dropdown-->
        <li class="nav-item dropdown no-caret d-lg-none me-3">
            <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="searchDropdown" href="#" role="button"
               data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i data-feather="search"></i>
            </a>
            <!-- Dropdown - Search-->
            <div class="dropdown-menu dropdown-menu-end animated--fade-in-up p-3 shadow"
                 aria-labelledby="searchDropdown">
                <form class="form-inline w-100 me-auto" asp-controller="Medicine" asp-action="List" method="get">
                    <div class="input-group input-group-joined input-group-solid">
@*                         <input class="form-control pe-0" type="text" placeholder="Search for..." aria-label="Search"
                               aria-describedby="basic-addon2" /> *@
						@Html.TextBox("Param", null, new { @class = "form-control pe-0", placeholder = "Search for..." })
                        <div class="input-group-text"><i data-feather="search"></i></div>
                    </div>
                </form>
            </div>
        </li>
            <partial name="_CartSummary" />
        </li>
        <!-- User Dropdown-->
        <li class="nav-item dropdown no-caret dropdown-user me-lg-4 me-3">
            <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownUserImage"
               href="javascript:void(0);" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
               aria-expanded="false">
                <img class="img-fluid" src="~/assets/img/developer-avatar.svg" />
            </a>
            <div class="dropdown-menu dropdown-menu-end animated--fade-in-up border-0 shadow"
                 aria-labelledby="navbarDropdownUserImage">
                <h6 class="dropdown-header d-flex align-items-center">
                    <div class="dropdown-item-icon me-1"><i data-feather="user"></i></div>
                    <div class="dropdown-user-details">
                        <div class="dropdown-user-details-name">@User?.Identity?.Name</div>
                    </div>
                </h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="Account" asp-action="Index">
                    <div class="dropdown-item-icon"><i data-feather="settings"></i></div>
                    Account
                </a>
                <a class="dropdown-item" href="#!" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    <div class="dropdown-item-icon"><i data-feather="log-out"></i></div>
                    Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <a asp-controller="Account" asp-action="Logout" class="btn btn-secondary">Logout</a>
            </div>
        </div>
    </div>
</div>

medicamento/Views/Shared/_Search.cshtml
<form class="d-none d-lg-inline-block form-inline me-md-3 my-md-0 my-2 me-0"
	  asp-controller="Medicine" asp-action="List" method="get">
	<div class="input-group input-group-joined">
		@Html.TextBox("Param", null, new { @class = "form-control border-0", placeholder = "Search" })
		@* <div class="input-group-append">
			<div class="input-group-text border-0">
				<i class="bi bi-search"></i>
			</div>
		</div> *@
	</div>
</form>

medicamento/Views/Shared/_SearchDropdown.cshtml
<form class="form-inline mr-auto"
	  asp-controller="Medicine" asp-action="List" method="get">
	<div class="input-group input-group">
		@Html.TextBox("Param", null, new { @class = "form-control border-0", placeholder = "Search" })
		@* <div class="input-group-append"> *@
			@* <button type="submit" id="submit" class="btn btn-primary">
				<i class="fas fa-search fa-sm"></i>
			</button> *@
			@* <div class="input-group-text border-0">
				<i class="bi bi-search"></i>
			</div> *@
		@* </div> *@
	</div>
</form>

medicamento/Views/Shared/_Sidebar.cshtml
<div id="layoutSidenav_nav">
	<nav class="sidenav shadow-right sidenav-light">
		<div class="sidenav-menu">
			<div class="nav accordion" id="accordionSidenav">
				<!-- Sidenav Menu Heading (Account)-->
				<!-- * * Note: * * Visible only on and above the sm breakpoint-->
				<div class="sidenav-menu-heading d-sm-none">Account</div>
				<!-- Sidenav Link (Alerts)-->
				<!-- * * Note: * * Visible only on and above the sm breakpoint-->
				<a class="nav-link d-sm-none" href="#!">
					<div class="nav-link-icon"><i data-feather="bell"></i></div>
					Alerts
					<span class="badge bg-warning-soft text-warning ms-auto">4 New!</span>
				</a>
				<!-- Sidenav Link (Messages)-->
				<!-- * * Note: * * Visible only on and above the sm breakpoint-->
				<a class="nav-link d-sm-none" asp-controller="ShoppingCart" asp-action="Index">
					<div class="nav-link-icon"><i data-feather="mail"></i></div>
					Messages
					<span class="badge bg-success-soft text-success ms-auto">2 New!</span>
				</a>
				@* <div class="sidenav-menu-heading">Core</div>
				<a class="nav-link collapsed" href="javascript:void(0);" data-bs-toggle="collapse"
				   data-bs-target="#collapseDashboards" aria-expanded="false"
				   aria-controls="collapseDashboards">
					<div class="nav-link-icon"><i data-feather="activity"></i></div>
					Order Management
					<div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
				</a>
				<div class="collapse" id="collapseDashboards" data-bs-parent="#accordionSidenav">
					<nav class="sidenav-menu-nested nav accordion" id="accordionSidenavPages">
						<a class="nav-link" asp-controller="Order" asp-action="Index">
							Default
							<span class="badge bg-primary-soft text-primary ms-auto">Updated</span>
						</a>
						<a class="nav-link" href="dashboard-2.html">Search Users</a>
						<a class="nav-link" href="dashboard-3.html">Affiliate</a>
						<a class="nav-link" href="#" data-bs-theme-value="dark">Dark Mode</a>
						<a class="nav-link" href="#" data-bs-theme-value="light">Light Mode</a>
					</nav>
				</div> *@

				<a class="nav-link" asp-controller="Home" asp-action="Index">
					<div class="nav-link-icon"><i data-feather="bar-chart"></i></div>
					Home
				</a>
				<a class="nav-link" asp-controller="Medicine" asp-action="Index">
					<div class="nav-link-icon"><i data-feather="filter"></i></div>
					Medicine
				</a>

				<a class="nav-link" asp-controller="Orders" asp-action="Index">
					<div class="nav-link-icon"><i data-feather="filter"></i></div>
					Orders
				</a>
				@if (User.IsInRole("Admin"))
				{
					<a class="nav-link" asp-controller="User" asp-action="Index">
						<div class="nav-link-icon"><i data-feather="filter"></i></div>
						User Magement
					</a>
				}

			</div>
		</div>
		<!-- Sidenav Footer-->
		@* <div class="sidenav-footer">
			<div class="sidenav-footer-content">
				<div class="sidenav-footer-subtitle">Logged in as:</div>
				<div class="sidenav-footer-title">Valerie Luna</div>
			</div>
		</div> *@
	</nav>
</div>

medicamento/Views/Shared/_SuccessAlert.cshtml
@if (TempData["SuccessMessage"] != null)
{
	<div class="alert alert-success alert-dismissible fade show" role="alert">
		<strong>Success!</strong> @TempData["SuccessMessage"]
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
}